// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNameList(arg1) {
  return window['go']['main']['App']['GetNameList'](arg1);
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}
