// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetNameList(arg1:string):Promise<Array<main.Person>>;

export function LoadFile():Promise<void>;
